[package]
name = "rpfm-backend"
version = "0.1.0"
authors = ["Julien Tregoat <jules@jules.nyc>"]
edition = "2018"

[dependencies]
postgres = "0.15"
envy = "0.4"
dotenv = "0.14.1"
serde = "1.0.91"
serde_derive = "1.0.91"

[dev-dependencies]
